# Generated by Django 3.0.7 on 2020-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
