# Generated by Django 3.0.7 on 2020-06-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='taker',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='takeranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='takeranswer',
            name='taker',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
        migrations.DeleteModel(
            name='QuizType',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
        migrations.DeleteModel(
            name='Taker',
        ),
        migrations.DeleteModel(
            name='TakerAnswer',
        ),
    ]
