# Generated by Django 3.0.7 on 2020-06-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='user_name',
        ),
    ]
