# Generated by Django 3.0.7 on 2020-06-21 04:41

from django.db import migrations, models
import social_media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_auto_20200620_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='user_info',
            field=models.TextField(blank=True, default='', null=True, validators=[social_media.validators.validate_dictionary_from_json]),
        ),
    ]
