# Generated by Django 3.0.7 on 2020-06-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_auto_20200620_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterspider',
            name='user_profile_pictures',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
