# Generated by Django 3.0.7 on 2020-06-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_twitterspider_user_profile_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterspider',
            name='followers',
            field=models.FileField(default='social_media/media/social_media/twitter/followers/default.txt', upload_to=''),
        ),
    ]
