# Generated by Django 3.0.7 on 2020-06-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_twitterspider_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='followers',
            field=models.TextField(verbose_name=''),
        ),
    ]
