# Generated by Django 3.0.7 on 2020-06-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_auto_20200626_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='followers',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
