# Generated by Django 3.0.7 on 2020-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_auto_20200626_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterspider',
            name='following',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
