# Generated by Django 3.0.7 on 2020-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_twitterspider_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='followers',
            field=models.TextField(blank=True, default='social_media/media/social_media/twitter/followers/default.txt', null=True),
        ),
        migrations.AlterField(
            model_name='twitterspider',
            name='following',
            field=models.TextField(blank=True, default='social_media/media/social_media/twitter/following/default.txt', null=True),
        ),
    ]
