# Generated by Django 3.0.7 on 2020-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0009_auto_20200626_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField()),
            ],
        ),
    ]
