# Generated by Django 3.0.7 on 2020-07-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_media.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0010_dummymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiKey',
            new_name='TumblrApiKey',
        ),
        migrations.CreateModel(
            name='TwitterApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('api_key', models.CharField(max_length=250)),
                ('api_secret', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=250)),
                ('access_token_secret', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TumblrSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('blog_name', models.CharField(max_length=20)),
                ('user_info', models.TextField(blank=True, default='', null=True, validators=[social_media.validators.validate_dictionary_from_json])),
                ('user_profile_pictures', models.TextField(blank=True, default='', null=True)),
                ('followers', models.TextField(blank=True, default='social_media/media/social_media/twitter/followers/default.txt', null=True)),
                ('following', models.TextField(blank=True, default='social_media/media/social_media/twitter/following/default.txt', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
