# Generated by Django 3.0.7 on 2020-07-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0012_twitterapikey_what'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterapikey',
            name='what',
        ),
    ]
