# Generated by Django 3.0.7 on 2020-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0014_auto_20200704_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumblrspider',
            name='blog_name',
            field=models.CharField(max_length=50),
        ),
    ]
