# Generated by Django 3.0.7 on 2020-07-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0016_redditapikey_redditspider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditspider',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='redditspider',
            name='following',
        ),
        migrations.RemoveField(
            model_name='redditspider',
            name='user_profile_pictures',
        ),
    ]
