# Generated by Django 3.0.7 on 2020-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0017_auto_20200704_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='user_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
