# Generated by Django 3.0.7 on 2020-07-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0020_auto_20200709_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='followers',
            field=models.FileField(blank=True, default='social_media/twitter/followers/default.txt', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='twitterspider',
            name='following',
            field=models.FileField(blank=True, default='social_media/twitter/following/default.txt', null=True, upload_to=''),
        ),
    ]
