# Generated by Django 3.0.7 on 2020-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0024_auto_20200710_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterspider',
            name='followers',
            field=models.FileField(blank=True, default='C:\\Users\\natha\\PycharmProjects\\cyber_eye\\media/media/social_media/twitter/followers/default.txt', max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='twitterspider',
            name='following',
            field=models.FileField(blank=True, default='C:\\Users\\natha\\PycharmProjects\\cyber_eye\\media/media/social_media/twitter/following/default.txt', max_length=200, null=True, upload_to=''),
        ),
    ]
